// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANmRmyxLq-wj-JvjHS3OTwm1S1B_YtKHw',
    appId: '1:161864337509:web:ab58ffac9b55fd2d8d5e8c',
    messagingSenderId: '161864337509',
    projectId: 'instagramclone-a89fc',
    authDomain: 'instagramclone-a89fc.firebaseapp.com',
    databaseURL: 'https://instagramclone-a89fc-default-rtdb.firebaseio.com',
    storageBucket: 'instagramclone-a89fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEFiJCo251uGLSCAxRilQ-cSGWR4-kbxM',
    appId: '1:161864337509:android:d6364b1dce40b1678d5e8c',
    messagingSenderId: '161864337509',
    projectId: 'instagramclone-a89fc',
    databaseURL: 'https://instagramclone-a89fc-default-rtdb.firebaseio.com',
    storageBucket: 'instagramclone-a89fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSNjWqtfn4v4ZKF4c934-dmy1PCPsHc44',
    appId: '1:161864337509:ios:36815064e49b7f7b8d5e8c',
    messagingSenderId: '161864337509',
    projectId: 'instagramclone-a89fc',
    databaseURL: 'https://instagramclone-a89fc-default-rtdb.firebaseio.com',
    storageBucket: 'instagramclone-a89fc.appspot.com',
    iosClientId: '161864337509-shf1gnlmlc64dsnh92ira2ej09hpsurh.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSNjWqtfn4v4ZKF4c934-dmy1PCPsHc44',
    appId: '1:161864337509:ios:bd9f9f3fb9dfb8fe8d5e8c',
    messagingSenderId: '161864337509',
    projectId: 'instagramclone-a89fc',
    databaseURL: 'https://instagramclone-a89fc-default-rtdb.firebaseio.com',
    storageBucket: 'instagramclone-a89fc.appspot.com',
    iosClientId: '161864337509-6kgvndqk10f21178vc1src3um2b6eep6.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramDemo.RunnerTests',
  );
}
